CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(name) <= 120),
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 11),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_accounts (
  student_id INTEGER PRIMARY KEY REFERENCES students(id) ON DELETE CASCADE,
  email TEXT NOT NULL CHECK (length(email) <= 254),
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS student_accounts_email_lower_unique
  ON student_accounts (lower(email));

CREATE TABLE IF NOT EXISTS student_drive_folders (
  student_id INTEGER PRIMARY KEY REFERENCES students(id) ON DELETE CASCADE,
  drive_folder_id TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS homeworks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (length(title) <= 160),
  instructions TEXT NOT NULL DEFAULT '',
  resource_url TEXT NOT NULL DEFAULT '',
  due_at TIMESTAMPTZ,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS homework_students (
  homework_id INTEGER NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  PRIMARY KEY (homework_id, student_id)
);

CREATE INDEX IF NOT EXISTS homework_students_student_id_idx
  ON homework_students (student_id, homework_id);

CREATE TABLE IF NOT EXISTS homework_submissions (
  homework_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('submitted', 'no_homework')),
  drive_file_id TEXT,
  file_name TEXT,
  score INTEGER CHECK (score IS NULL OR score BETWEEN 0 AND 12),
  feedback TEXT NOT NULL DEFAULT '',
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  graded_at TIMESTAMPTZ,
  PRIMARY KEY (homework_id, student_id),
  FOREIGN KEY (homework_id, student_id)
    REFERENCES homework_students(homework_id, student_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS homework_submissions_student_date_idx
  ON homework_submissions (student_id, submitted_at);