ALTER TABLE homeworks
  ADD COLUMN IF NOT EXISTS next_lesson_at DATE,
  ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS demo_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS homeworks_demo_key_unique
  ON homeworks (demo_key)
  WHERE demo_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS textbooks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 11),
  subject TEXT NOT NULL CHECK (length(subject) <= 80),
  title TEXT NOT NULL CHECK (length(title) <= 180),
  author TEXT NOT NULL DEFAULT '' CHECK (length(author) <= 160),
  url TEXT NOT NULL CHECK (url ~* '^https?://'),
  resource_type TEXT NOT NULL DEFAULT 'textbook'
    CHECK (resource_type IN ('textbook', 'practice')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_demo BOOLEAN NOT NULL DEFAULT FALSE,
  demo_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS textbooks_demo_key_unique
  ON textbooks (demo_key)
  WHERE demo_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS textbooks_grade_subject_order_idx
  ON textbooks (grade, subject, sort_order, id);