-- NUS (Nowa Ukrainska Shkola - New Ukrainian School) topics and materials storage

CREATE TABLE IF NOT EXISTS nush_topics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 11),
  title TEXT NOT NULL CHECK (length(title) <= 160),
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS nush_topics_grade_idx ON nush_topics (grade);

CREATE TABLE IF NOT EXISTS nush_topic_materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id INTEGER NOT NULL REFERENCES nush_topics(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(name) <= 160),
  url TEXT NOT NULL,
  material_type TEXT NOT NULL CHECK (material_type IN ('google_drive', 'naurok', 'pdf', 'doc', 'link', 'other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS nush_topic_materials_topic_id_idx ON nush_topic_materials (topic_id);

-- Classes and materials (replacing in-memory storage)

CREATE TABLE IF NOT EXISTS material_classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(name) <= 120),
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 11),
  drive_folder_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS material_classes_grade_idx ON material_classes (grade);

CREATE TABLE IF NOT EXISTS material_topics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER NOT NULL REFERENCES material_classes(id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (length(title) <= 160),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS material_topics_class_id_idx ON material_topics (class_id);

CREATE TABLE IF NOT EXISTS material_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id INTEGER NOT NULL REFERENCES material_topics(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(name) <= 160),
  url TEXT NOT NULL,
  file_type TEXT NOT NULL CHECK (file_type IN ('pdf', 'doc', 'image', 'link', 'other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS material_files_topic_id_idx ON material_files (topic_id);
