-- Student personal textbooks

CREATE TABLE IF NOT EXISTS student_textbooks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (length(title) <= 160),
  url TEXT NOT NULL,
  subject TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_textbooks_student_id_idx ON student_textbooks (student_id);
CREATE INDEX IF NOT EXISTS student_textbooks_subject_idx ON student_textbooks (student_id, subject);
