-- A homework submission can contain several files. Existing single-file rows are copied over.
CREATE TABLE IF NOT EXISTS homework_submission_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  drive_file_id TEXT NOT NULL,
  file_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (homework_id, student_id)
    REFERENCES homework_submissions(homework_id, student_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS homework_submission_files_submission_idx
  ON homework_submission_files (homework_id, student_id);

INSERT INTO homework_submission_files (homework_id, student_id, drive_file_id, file_name)
SELECT homework_id, student_id, drive_file_id, file_name
FROM homework_submissions sub
WHERE drive_file_id IS NOT NULL AND file_name IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM homework_submission_files f
    WHERE f.homework_id = sub.homework_id AND f.student_id = sub.student_id
  );
