-- Hourly price per student in UAH. Held lessons keep their own copy of the rate.
ALTER TABLE students
  ADD COLUMN IF NOT EXISTS hourly_rate INTEGER NOT NULL DEFAULT 0
  CHECK (hourly_rate BETWEEN 0 AND 100000);

-- Weekly lesson slots in Kyiv local time. Changing a schedule closes old slots with ends_on so past lessons keep their dates.
CREATE TABLE IF NOT EXISTS student_lesson_slots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 1 AND 7),
  start_time TIME NOT NULL,
  duration_minutes INTEGER NOT NULL DEFAULT 60 CHECK (duration_minutes BETWEEN 15 AND 240),
  starts_on DATE NOT NULL,
  ends_on DATE
);

CREATE INDEX IF NOT EXISTS student_lesson_slots_student_idx
  ON student_lesson_slots (student_id);

-- One row per lesson that was marked, moved or added by hand. Slot occurrences without a row are still planned.
CREATE TABLE IF NOT EXISTS lessons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  scheduled_at TIMESTAMPTZ NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes BETWEEN 15 AND 240),
  status TEXT NOT NULL CHECK (status IN ('planned', 'held', 'cancelled')),
  is_extra BOOLEAN NOT NULL DEFAULT FALSE,
  hourly_rate INTEGER NOT NULL DEFAULT 0 CHECK (hourly_rate >= 0),
  UNIQUE (student_id, scheduled_at)
);

CREATE INDEX IF NOT EXISTS lessons_starts_at_idx
  ON lessons (starts_at);
