-- Money received from parents. The balance is held lessons minus the sum of these payments.
CREATE TABLE IF NOT EXISTS student_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  paid_on DATE NOT NULL,
  amount INTEGER NOT NULL CHECK (amount BETWEEN 1 AND 1000000),
  note TEXT NOT NULL DEFAULT '' CHECK (char_length(note) <= 200),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_payments_student_idx
  ON student_payments (student_id);

CREATE INDEX IF NOT EXISTS student_payments_paid_on_idx
  ON student_payments (paid_on);
