export const router = {
  home: "/",
  students: "/students",
  schedule: "/schedule",
  homework: "/homework",
  materials: "/materials",
  student: "/student",
  login: "/login",
  studentView: (studentId: number) => `/students/${studentId}`,
  api: {
    students: "/api/students",
    student: (studentId: number) => `/api/students?id=${studentId}`,
    studentTextbooks: (studentId: number) => `/api/students/${studentId}/textbooks`,
    studentDriveFolder: (studentId: number) => `/api/students/${studentId}/drive-folder`,
    studentSchedule: (studentId: number) => `/api/students/${studentId}/schedule`,
    schedule: "/api/schedule",
    payments: "/api/payments",
    materials: "/api/materials",
    nush: "/api/nush",
    textbooks: "/api/textbooks",
    textbook: (textbookId: number) => `/api/textbooks/${textbookId}`,
    assignments: "/api/assignments",
    assignment: (homeworkId: number) => `/api/assignments/${homeworkId}`,
    homeworkSubmission: (homeworkId: number) => `/api/assignments/${homeworkId}/submission`,
    homeworkNoHomework: (homeworkId: number) => `/api/assignments/${homeworkId}/no-homework`,
    homeworkGrade: (homeworkId: number) => `/api/assignments/${homeworkId}/grade`,
    studentDashboard: "/api/student/dashboard",
    driveStatus: "/api/teacher/drive-status",
    drivePicker: "/api/teacher/drive-picker",
    changePassword: "/api/student/change-password",
  },
} as const;

export const navItems = [
  { href: router.home, label: "Огляд" },
  { href: router.students, label: "Учні" },
  { href: router.schedule, label: "Розклад і бюджет" },
  { href: router.homework, label: "Домашні завдання" },
  { href: router.materials, label: "Матеріали" },
] as const;
